version: '3.7'

services:

  server:
    build:
      context: ./services/server
      dockerfile: Dockerfile
    volumes:
      - './services/server:/usr/src/app'
    ports:
      - 5001:5000
    environment: 
     - FLASK_ENV=development
     - APP_SETTINGS=project.config.DevConfig
     - DATABASE_URL=postgres://postgres:postgres@server-db:5432/server_dev 
     - DATABASE_TEST_URL=postgres://postgres:postgres@server-db:5432/server_test
     - SECRET_KEY=supersecretkey
     - BASE_URL=http://localhost
    depends_on: 
      - server-db

  server-db:
    build:
      context: ./services/server/project/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  nginx:
    build:
      context:  ./services/nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
    depends_on:
      - server
      - client

  client:
    build:
      context: ./services/client
      dockerfile: Dockerfile
    volumes:
      - './services/client:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - 3007:3000
    environment: 
      - NODE_ENV=development
      - REACT_APP_SERVER_SERVICE_URL=${REACT_APP_SERVER_SERVICE_URL}
    depends_on:
      - server

  swagger:
    build:
      context: ./services/swagger
      dockerfile: Dockerfile  
    volumes:
      - './services/swagger/swagger.yaml:/usr/share/nginx/html/swagger.yaml'
    ports:
      - 3008:8080
    environment:
      - URL=swagger.yaml
    depends_on:
      - server