version: '3.7'

services:

  server:
    build:
      context: ./services/server
      dockerfile: Dockerfile-prod
    expose:
      - 5000
    environment: 
     - FLASK_ENV=production
     - APP_SETTINGS=project.config.ProdConfig
     - DATABASE_URL=postgres://postgres:postgres@server-db:5432/server_prod
     - DATABASE_TEST_URL=postgres://postgres:postgres@server-db:5432/server_test
     - SECRET_KEY=${SECRET_KEY}
    depends_on: 
      - server-db

  server-db:
    build:
      context: ./services/server/project/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  nginx:
    build:
      context:  ./services/nginx
      dockerfile: Dockerfile-prod
    restart: always
    ports:
      - 80:80
    depends_on:
      - server
      - client

  client:
    container_name: client
    build:
      context: ./services/client
      dockerfile: Dockerfile-prod
      args:
        - NODE_ENV=production
        - REACT_APP_SERVER_SERVICE_URL=${REACT_APP_SERVER_SERVICE_URL}
    ports:
      - 3007:80
    depends_on: 
      - server